"""
Application configuration and extension instances.

This module creates the Flask app and initializes every extension
(SQLAlchemy, Migrate, Bcrypt, JWTManager, Api, CORS) exactly once, so
that app.py, models.py, and seed.py can all import the same instances
without causing circular imports.
"""
import os
from datetime import timedelta

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_restful import Api
from flask_jwt_extended import JWTManager
from flask_cors import CORS
from sqlalchemy import MetaData

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

app = Flask(__name__)

# --- Core config -----------------------------------------------------------
app.config["SQLALCHEMY_DATABASE_URI"] = os.environ.get(
    "DATABASE_URL", f"sqlite:///{os.path.join(BASE_DIR, 'app.db')}"
)
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.json.compact = False

# --- JWT config --------------------------------------------------------
app.config["JWT_SECRET_KEY"] = os.environ.get(
    "JWT_SECRET_KEY", "dev-secret-key-change-me-in-production"
)
app.config["JWT_ACCESS_TOKEN_EXPIRES"] = timedelta(days=1)

# --- Naming convention keeps autogenerated migrations consistent ----------
metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)

db = SQLAlchemy(metadata=metadata)
db.init_app(app)
migrate = Migrate(app, db)
bcrypt = Bcrypt(app)
jwt = JWTManager(app)
api = Api(app)

# Allow the React frontend (running on a different port) to send requests,
# including the Authorization header used for JWT auth.
CORS(app)
